version: '3'
services:
  dockerhub:
    build: .
    ports:
      - 3000:3000
    environment:
      - TOKEN=abc123
    volumes:
      - ./scripts:/src/scripts
      - /var/run/docker.sock:/var/run/docker.sock
      # Path to docker-compose files who are triggered by scripts:
      # - /srv:/srv
